Desktop/djangopractice/app1/urls.py
from django.urls import path
from.import views

app_name="app1"

urlpatterns = [

    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('hai/<name>/',views.hainame,name="hai"),
    path('add/<a>/<b>',views.add,name="add"),
    path('tempdemo/',views.tempdemo,name="tempdemo"),
    path('grt2/<a>/<b>',views.grt2,name="grt2"),
    path('indextax',views.indextax,name="indextax"),
    path('homepage/',views.hometemp,name="homepage"),
    path('aboutus/',views.abouttemp,name="aboutus"),
    path('register/',views.registertemp,name="register"),




]

Desktop/djangopractice/tenant_tax/urls.py
from django.contrib import admin
from django.urls import path, include
# from app import views
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app1.urls")),

#    # path('',views.index,name="index"),
#     path('home/',views.home,name="home"),
#     path('hai/<name>/',views.hainame,name="hai"),
#     path('add/<a>/<b>',views.add,name="add"),
#     path('tempdemo/',views.tempdemo,name="tempdemo"),
#     path('grt2/<a>/<b>',views.grt2,name="grt2"),
#     path('indextax',views.indextax,name="indextax"),
#     path('homepage/',views.hometemp,name="homepage"),
#     path('aboutus/',views.abouttemp,name="aboutus"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Desktop/djangopractice/app1/models.py
from django.db import models

# Create your models here.

Desktop/djangopractice/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage


# Create your views here.
def index(request):
    return HttpResponse('<h1>Welcome to the project</h1>')

def home(request):
    return HttpResponse('<h1>Welcome to the Home</h1>')

def hainame(request,name):
    return HttpResponse('<h2>hello {}</h2>'.format(name))

def add(request, a, b):
    return HttpResponse("<h1> the sum of {} and {} = {}</h1>".format(a,b,int(a)+int(b)))

def tempdemo(request):
    fruits=['apple','mango', 'guava','chikk']
    return render(request,'template.html',context={'name':'akash','fruits':fruits})


def grt2(request,a,b):
    return render(request,'template2.html',context={'a':a,'b':b})

def indextax(request):
    return render(request,'indextax.html')

def hometemp(request):
    return render(request,'pages/home.html')

def abouttemp(request):
    return render(request,'pages/about.html')

def registertemp(request):
    if request.method=="POST":
        name=request.POST.get("fname")
        lname=request.POST.get("lname")
        file=None
        if request.FILES:
            file= request.FILES['profilepic']
            fs=FileSystemStorage()
            savedfile=fs.save(file.name,file)
            file_url=fs.url(savedfile)

        return HttpResponse("<h1>Form submitted successfully {} <br> verify the details <br> name: {} <br> email: {} <br> profilepic :<img src='{}'> ".format(name,name,lname,file_url))

    return render(request,'pages/register.html')

Desktop/djangopractice/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block title %}
    <title>Base html</title>
    {% endblock %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>

   <!-- including the navbar partial-->

   {% include "partial/_navbar.html"  %}

    {% block content %} 

    <h1> Base page</h1>
    
    {% endblock %}


</body>
</html>

Desktop/djangopractice/templates/indextax.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TenantTax</title>
    <link rel="icon" href="Pics/building.png" sizes="96x96" type="image/png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">


</head>

<body>
    <header>
        <div class="parent">
            <div id="logo">
                <img src="{% static 'images/TenantTaxlogos.png' %}" height="75px" width="70px">

            </div>
            <div id="heading">
                TenantTax
            </div>
        </div>
    </header>

    <nav class="anchor">
        
        <a href=""><i class = "fa-solid fa-house-user"></i> &nbsp;Home</a>
        <a href=""><i class="fa-solid fa-building"></i>&nbsp;Property Tax</a>
        <a href=""><i class="fa-solid fa-money-check"></i> &nbsp;Payment Status</a>
        <div class="helpline">
            <a href="" class="helpline"> <i class="fa-solid fa-phone-volume"></i>&nbsp;Helpline</a>
            <section class="drop">
                <p>
                    <center><u>TenantTax</u></center>
                </p>
                <ul style="padding-bottom: 60px;">
                    <li>
                        +91-9865348765
                    </li>
                    <li>
                        +91-9854186549
                    </li>
                </ul>

            </section>

        </div>






    </nav>

    <section>
        <div class="body">
            <div class = "decImg">
                <div id="mainImg">
                    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img src="{% static 'images/home1.jpeg' %}" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img src="{% static 'images/home2.jpg' %}" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img src="{% static 'images/home3.png' %}" class="d-block w-100" alt="...">
                          </div>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </button>
                      </div>


                   
    
                </div>

            </div>

        
            <div id="login" class="div_2">

                <h3>Login </h3>
                <br>
                <form action="/action_page.php" method="post">

                    <div class="container">
                        <label for="uname"><b>Username</b></label><br>
                        <input type="text" placeholder="Enter Username" name="uname" required> <br>

                        <label for="psw"><b>Password</b></label> <br>
                        <input type="password" placeholder="Enter Password" name="psw" required> <br> <br>

                        <button type="submit">Login</button>

                    </div>

                </form>
                <br>

                <a href="">Don't have a an Account!! <br>
                    Create one
            </div></a>



        </div>
        </div>




    </section>
    <footer>
        <i class="fa-regular fa-copyright" style="margin-top: 10px;"></i> &nbsp; 2020 Company - All Rights Reserved

    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>


</body>

</html>

Desktop/djangopractice/templates/pages/about.html
{% extends "base.html" %}
{% load static %} 
 

{% block title %}
    <title>About Page</title>
    {% endblock %}


{% block content %} 
    <div class="container"> 
    <h1> Aboutpage</h1>
    </div>
    
{% endblock %}

Desktop/djangopractice/templates/pages/home.html
{% extends "base.html" %}
{% load static %} 
 

{% block title %}
    <title>Home Page</title>
    {% endblock %}


{% block content %} 
    <div class="container"> 
    <h1> Home page</h1>
    </div>
    
{% endblock %}

Desktop/djangopractice/templates/pages/register.html
{% extends "base.html" %}
{% load static %} 
 

{% block title %}
    <title>RegisterPage</title>
    {% endblock %}


{% block content %} 
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="fname">First name:</label><br>
        <input type="text" id="fname" name="fname" value="John"><br>
        <label for="lname">Last name:</label><br>
        <input type="text" id="lname" name="lname" value="Doe"><br><br>
        <input type="file" name="profilepic" id="profilepic">
        <input type="submit" value="Submit">
    </form> 
    <h1> Registerpage</h1>
    
{% endblock %}

Desktop/djangopractice/templates/partial/_navbar.html
{% load static %} 
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'app1:homepage' %}">Home</a></li>
              <li><a class="dropdown-item" href="{% url 'app1:aboutus' %}">About</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'app1:register' %}">Register</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

Desktop/djangopractice/templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    <h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, velit. Perferendis aliquam, 
        ipsam doloremque ab voluptatum nihil sit suscipit provident assumenda iusto modi esse sequi reiciendis, soluta possimus, est non!</h1>

        <h1>
            Hello {{name}}
        </h1>
        <ol>
            {%for fruit in fruits%}
            <li>
                {{fruit}}
            </li>

            {%endfor%}
        </ol>
        <h1><a href="{% url 'grt2' a=10 b=4 %}">Template</a></h1>
</body>
</html>

Desktop/djangopractice/templates/template2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    {% if a > b %}
        <h1> {{a}}</h1>
    {% else %}
        <h1>  {{b}}</h1>
    {% endif %}

    <h1> <a href="{% url 'tempdemo' %}">Template</a></h1>
    <img src="{% static 'images/tree.jpg' %}" height="100px" width="100px" alt="">
</body>
</html>